version: "3.3"

services:
  api:
    build:
      context: ./openAPI
    ports:
      - "80:80"
    env_file:
      - ~/env.txt
    command: python3 -u -m openapi_server

volumes:
  cache:
    driver: local
