import os


STRIPE_API_KEY = os.getenv("STRIPE_API_KEY")
PUBLISHABLE_KEY = os.getenv("PUBLISHABLE_KEY")
TMP_API_SECRET_KEY = os.getenv("TMP_API_SECRET_KEY")
TMP_APPLICATION_SECRET_KEY = os.getenv("TMP_APPLICATION_SECRET_KEY")
TMP_DEVICE_SECRET_KEY = os.getenv("TMP_DEVICE_SECRET_KEY")
POSTGRESQL_PASSWORD = os.getenv("POSTGRESQL_PASSWORD")