# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PhoneNumber(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, country_code=None, area_code=None, phone_number=None):  # noqa: E501
        """PhoneNumber - a model defined in OpenAPI

        :param country_code: The country_code of this PhoneNumber.  # noqa: E501
        :type country_code: int
        :param area_code: The area_code of this PhoneNumber.  # noqa: E501
        :type area_code: int
        :param phone_number: The phone_number of this PhoneNumber.  # noqa: E501
        :type phone_number: int
        """
        self.openapi_types = {
            'country_code': int,
            'area_code': int,
            'phone_number': int
        }

        self.attribute_map = {
            'country_code': 'country_code',
            'area_code': 'area_code',
            'phone_number': 'phone_number'
        }

        self._country_code = country_code
        self._area_code = area_code
        self._phone_number = phone_number

    @classmethod
    def from_dict(cls, dikt) -> 'PhoneNumber':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PhoneNumber of this PhoneNumber.  # noqa: E501
        :rtype: PhoneNumber
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_code(self):
        """Gets the country_code of this PhoneNumber.


        :return: The country_code of this PhoneNumber.
        :rtype: int
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this PhoneNumber.


        :param country_code: The country_code of this PhoneNumber.
        :type country_code: int
        """

        self._country_code = country_code

    @property
    def area_code(self):
        """Gets the area_code of this PhoneNumber.


        :return: The area_code of this PhoneNumber.
        :rtype: int
        """
        return self._area_code

    @area_code.setter
    def area_code(self, area_code):
        """Sets the area_code of this PhoneNumber.


        :param area_code: The area_code of this PhoneNumber.
        :type area_code: int
        """

        self._area_code = area_code

    @property
    def phone_number(self):
        """Gets the phone_number of this PhoneNumber.


        :return: The phone_number of this PhoneNumber.
        :rtype: int
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this PhoneNumber.


        :param phone_number: The phone_number of this PhoneNumber.
        :type phone_number: int
        """

        self._phone_number = phone_number
