# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.name import Name
from openapi_server.models.phone_number import PhoneNumber
from openapi_server.models.update_payment_amount import UpdatePaymentAmount
from openapi_server import util

from openapi_server.models.name import Name  # noqa: E501
from openapi_server.models.phone_number import PhoneNumber  # noqa: E501
from openapi_server.models.update_payment_amount import UpdatePaymentAmount  # noqa: E501

class UpdateUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payment_amount=None, country_code=None, area_code=None, phone_number=None, first_name=None, last_name=None):  # noqa: E501
        """UpdateUser - a model defined in OpenAPI

        :param payment_amount: The payment_amount of this UpdateUser.  # noqa: E501
        :type payment_amount: float
        :param country_code: The country_code of this UpdateUser.  # noqa: E501
        :type country_code: int
        :param area_code: The area_code of this UpdateUser.  # noqa: E501
        :type area_code: int
        :param phone_number: The phone_number of this UpdateUser.  # noqa: E501
        :type phone_number: int
        :param first_name: The first_name of this UpdateUser.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this UpdateUser.  # noqa: E501
        :type last_name: str
        """
        self.openapi_types = {
            'payment_amount': float,
            'country_code': int,
            'area_code': int,
            'phone_number': int,
            'first_name': str,
            'last_name': str
        }

        self.attribute_map = {
            'payment_amount': 'payment_amount',
            'country_code': 'country_code',
            'area_code': 'area_code',
            'phone_number': 'phone_number',
            'first_name': 'first_name',
            'last_name': 'last_name'
        }

        self._payment_amount = payment_amount
        self._country_code = country_code
        self._area_code = area_code
        self._phone_number = phone_number
        self._first_name = first_name
        self._last_name = last_name

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateUser of this UpdateUser.  # noqa: E501
        :rtype: UpdateUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_amount(self):
        """Gets the payment_amount of this UpdateUser.


        :return: The payment_amount of this UpdateUser.
        :rtype: float
        """
        return self._payment_amount

    @payment_amount.setter
    def payment_amount(self, payment_amount):
        """Sets the payment_amount of this UpdateUser.


        :param payment_amount: The payment_amount of this UpdateUser.
        :type payment_amount: float
        """

        self._payment_amount = payment_amount

    @property
    def country_code(self):
        """Gets the country_code of this UpdateUser.


        :return: The country_code of this UpdateUser.
        :rtype: int
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this UpdateUser.


        :param country_code: The country_code of this UpdateUser.
        :type country_code: int
        """

        self._country_code = country_code

    @property
    def area_code(self):
        """Gets the area_code of this UpdateUser.


        :return: The area_code of this UpdateUser.
        :rtype: int
        """
        return self._area_code

    @area_code.setter
    def area_code(self, area_code):
        """Sets the area_code of this UpdateUser.


        :param area_code: The area_code of this UpdateUser.
        :type area_code: int
        """

        self._area_code = area_code

    @property
    def phone_number(self):
        """Gets the phone_number of this UpdateUser.


        :return: The phone_number of this UpdateUser.
        :rtype: int
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this UpdateUser.


        :param phone_number: The phone_number of this UpdateUser.
        :type phone_number: int
        """

        self._phone_number = phone_number

    @property
    def first_name(self):
        """Gets the first_name of this UpdateUser.


        :return: The first_name of this UpdateUser.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UpdateUser.


        :param first_name: The first_name of this UpdateUser.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UpdateUser.


        :return: The last_name of this UpdateUser.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UpdateUser.


        :param last_name: The last_name of this UpdateUser.
        :type last_name: str
        """

        self._last_name = last_name
