# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdatePaymentAmount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payment_amount=None):  # noqa: E501
        """UpdatePaymentAmount - a model defined in OpenAPI

        :param payment_amount: The payment_amount of this UpdatePaymentAmount.  # noqa: E501
        :type payment_amount: float
        """
        self.openapi_types = {
            'payment_amount': float
        }

        self.attribute_map = {
            'payment_amount': 'payment_amount'
        }

        self._payment_amount = payment_amount

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatePaymentAmount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdatePaymentAmount of this UpdatePaymentAmount.  # noqa: E501
        :rtype: UpdatePaymentAmount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_amount(self):
        """Gets the payment_amount of this UpdatePaymentAmount.


        :return: The payment_amount of this UpdatePaymentAmount.
        :rtype: float
        """
        return self._payment_amount

    @payment_amount.setter
    def payment_amount(self, payment_amount):
        """Sets the payment_amount of this UpdatePaymentAmount.


        :param payment_amount: The payment_amount of this UpdatePaymentAmount.
        :type payment_amount: float
        """

        self._payment_amount = payment_amount
