# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdatePaymentAmount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, new_payment_amount=None):  # noqa: E501
        """UpdatePaymentAmount - a model defined in OpenAPI

        :param new_payment_amount: The new_payment_amount of this UpdatePaymentAmount.  # noqa: E501
        :type new_payment_amount: float
        """
        self.openapi_types = {
            'new_payment_amount': float
        }

        self.attribute_map = {
            'new_payment_amount': 'new_payment_amount'
        }

        self._new_payment_amount = new_payment_amount

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatePaymentAmount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdatePaymentAmount of this UpdatePaymentAmount.  # noqa: E501
        :rtype: UpdatePaymentAmount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_payment_amount(self):
        """Gets the new_payment_amount of this UpdatePaymentAmount.


        :return: The new_payment_amount of this UpdatePaymentAmount.
        :rtype: float
        """
        return self._new_payment_amount

    @new_payment_amount.setter
    def new_payment_amount(self, new_payment_amount):
        """Sets the new_payment_amount of this UpdatePaymentAmount.


        :param new_payment_amount: The new_payment_amount of this UpdatePaymentAmount.
        :type new_payment_amount: float
        """

        self._new_payment_amount = new_payment_amount
